# Generated by Django 4.2.2 on 2023-06-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='employee_uploads/'),
        ),
        migrations.AlterField(
            model_name='employer_user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='employer_uploads/'),
        ),
    ]
