# Generated by Django 4.2.2 on 2023-06-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_employee_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='employer_user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
