# Generated by Django 4.2.2 on 2023-07-16 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=rest_api.models.upload_employer_file)),
                ('about_company', models.CharField(blank=True, max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.post')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('skills_required', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('employer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='rest_api.employer_user')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_birth', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=15)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=rest_api.models.upload_employee_file)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('about_me', models.CharField(blank=True, max_length=2000, null=True)),
                ('work_experience', models.CharField(blank=True, max_length=500, null=True)),
                ('education', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.post')),
            ],
        ),
        migrations.CreateModel(
            name='Application_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('resume', models.FileField(blank=True, null=True, upload_to=rest_api.models.upload_app_file)),
                ('cover_letter', models.TextField()),
                ('Job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.job')),
            ],
        ),
    ]
